# Use the official postgis image
FROM postgis/postgis:16-3.4

# Set environment variables
ENV POSTGRES_DB=db
ENV POSTGRES_USER=123
ENV POSTGRES_PASSWORD=123

# Expose the PostgreSQL port
EXPOSE 5432

